services:
  _defaults:
    public: true

  mbo.cache.directory_provider:
    class: 'PrestaShop\Module\Mbo\Cache\CacheDirectoryProvider'
    arguments:
      - !php/const _PS_ROOT_DIR_
      - !php/const _PS_MODE_DEV_

  mbo.external_content.circuit_breaker.doctrine_cache:
    class: Doctrine\Common\Cache\FilesystemCache
    arguments:
      - '@=service("mbo.cache.directory_provider").getPath() ~ "/mbo_circuit_breaker"'

  mbo.external_content.circuit_breaker.guzzle.cache_storage:
    class: GuzzleHttp\Subscriber\Cache\CacheStorage
    arguments:
      - '@mbo.external_content.circuit_breaker.doctrine_cache'
      - "mbo_circuit_breaker_"
      - !php/const \PrestaShop\Module\Mbo\ExternalContentProvider\ExternalContentProvider::CACHE_DURATION

  mbo.external_content.circuit_breaker.guzzle.cache_subscriber_factory:
    class: PrestaShop\Module\Mbo\Cache\CacheSubscriberFactory

  mbo.external_content.circuit_breaker.guzzle.cache_subscriber:
    class: GuzzleHttp\Subscriber\Cache\CacheSubscriber
    factory: ['@mbo.external_content.circuit_breaker.guzzle.cache_subscriber_factory', 'create']
    arguments:
      - "@mbo.external_content.circuit_breaker.guzzle.cache_storage"

  mbo.external_content.circuit_breaker.storage:
    class: PrestaShop\CircuitBreaker\Storage\DoctrineCache
    arguments:
      - '@mbo.external_content.circuit_breaker.doctrine_cache'

  mbo.external_content.circuit_breaker.advanced_factory:
    class: PrestaShop\CircuitBreaker\AdvancedCircuitBreakerFactory

  mbo.external_content.circuit_breaker.settings:
    class: PrestaShop\CircuitBreaker\FactorySettings
    arguments:
      - !php/const \PrestaShop\Module\Mbo\ExternalContentProvider\ExternalContentProvider::CLOSED_ALLOWED_FAILURES
      - !php/const \PrestaShop\Module\Mbo\ExternalContentProvider\ExternalContentProvider::CLOSED_TIMEOUT_SECONDS
      - !php/const \PrestaShop\Module\Mbo\ExternalContentProvider\ExternalContentProvider::OPEN_THRESHOLD_SECONDS
    calls:
      - ['setStrippedFailures', [!php/const \PrestaShop\Module\Mbo\ExternalContentProvider\ExternalContentProvider::OPEN_ALLOWED_FAILURES]]
      - ['setStrippedTimeout', [!php/const \PrestaShop\Module\Mbo\ExternalContentProvider\ExternalContentProvider::OPEN_TIMEOUT_SECONDS]]
      - ['setStorage', ['@mbo.external_content.circuit_breaker.storage']]
      - ['setClientOptions', [{'method': 'GET', 'subscribers': ['@mbo.external_content.circuit_breaker.guzzle.cache_subscriber']}]]

  mbo.external_content.circuit_breaker:
    class: 'PrestaShop\CircuitBreaker\Contract\CircuitBreakerInterface'
    factory: ["@mbo.external_content.circuit_breaker.advanced_factory", create]
    arguments:
      - "@mbo.external_content.circuit_breaker.settings"

  mbo.externalcontent.provider:
    class: 'PrestaShop\Module\Mbo\ExternalContentProvider\ExternalContentProvider'
    arguments:
      - '@mbo.external_content.circuit_breaker'

  mbo.adapter.module_collection_data_provider:
    class: 'PrestaShop\Module\Mbo\ModuleCollectionDataProvider'
    arguments:
      - '@prestashop.core.admin.data_provider.module_interface'
      - '@prestashop.core.admin.module.repository'
      - '@prestashop.adapter.presenter.module'
      - '@prestashop.core.admin.tab.repository'
      - '@prestashop.adapter.legacy.context'

  mbo.tab.collection.factory:
    class: 'PrestaShop\Module\Mbo\Tab\TabCollectionFactory'
    arguments:
      - '@mbo.adapter.module_collection_data_provider'

  mbo.tab.collection.provider:
    class: 'PrestaShop\Module\Mbo\Tab\TabCollectionProvider'
    arguments:
      - '@prestashop.adapter.legacy.context'
      - '@mbo.externalcontent.provider'
      - '@mbo.tab.collection.factory'
      - '@doctrine.cache.provider'

  mbo.recommendedlinks.provider:
    class: 'PrestaShop\Module\Mbo\RecommendedLink\RecommendedLinkProvider'
    arguments:
      - '@prestashop.adapter.legacy.context'
      - '@serializer'

  mbo.recommendedmodules.presenter:
    class: 'PrestaShop\Module\Mbo\RecommendedModule\RecommendedModulePresenter'

  mbo.addons_selection_link_provider:
    class: 'PrestaShop\Module\Mbo\AddonsSelectionLinkProvider'
    arguments:
      - '@prestashop.core.foundation.version'
      - '@prestashop.adapter.legacy.context'
      - '@prestashop.adapter.legacy.configuration'
      - '@request_stack'

  mbo.controller.modules.catalog:
    class: 'PrestaShop\Module\Mbo\Controller\Admin\ModuleCatalogController'

  mbo.controller.modules.selection:
    class: 'PrestaShop\Module\Mbo\Controller\Admin\ModuleSelectionController'
    arguments:
      - '@request_stack'
      - '@mbo.externalcontent.provider'
      - '@mbo.addons_selection_link_provider'

  mbo.controller.modules.recommended:
    class: 'PrestaShop\Module\Mbo\Controller\Admin\ModuleRecommendedController'
    arguments:
      - '@request_stack'
      - '@mbo.tab.collection.provider'
      - '@mbo.recommendedmodules.presenter'

  mbo.controller.themes.catalog:
    class: 'PrestaShop\Module\Mbo\Controller\Admin\ThemeCatalogController'
    arguments:
      - '@request_stack'
      - '@mbo.externalcontent.provider'
      - '@mbo.addons_selection_link_provider'
